sudo: required

language: ruby

cache: docker

services:
  - docker

install: true

before_script:
  - docker-compose up -d

script:
  - docker-compose exec web rake test

after_script:
  - docker-compose down
