sudo: required

language: ruby

cache: docker

services:
  - docker

env:
  - global:
    - DOCKER_COMPOSE_VERSION: 2
    - REPO=prontotools/pronto-woo-notifier
    - COMMIT=${TRAVIS_COMMIT::8}

install: true

script:
  - docker-compose -f docker-compose.test.yml run sut

after_success:
  - bash deploy.sh

after_script:
  - docker-compose down
