sudo: required

language: ruby

services:
  - docker

install: true

before_script:
  - docker-compose up -d
  - sleep 5
  - docker-compose exec web rake db:create
  - docker-compose exec web rake db:migrate

script:
  - docker-compose exec web rake test

after_script:
  - docker-compose down
