sudo: required

language: ruby

cache: docker

services:
  - docker

env:
  - global:
    - DOCKER_COMPOSE_VERSION: 2
    - REPO=prontotools/pronto-woo-notifier
    - COMMIT=${TRAVIS_COMMIT::8}

install: true

# before_script:
#   -docker-compose -f docker-compose.test.yml build

script:
  - docker-compose -f docker-compose.test.yml run sut

after_script:
  - docker-compose down

after_success:
  - docker build -t $REPO:$COMMIT ./compose/rails/Dockerfile
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $REPO;
