sudo: required

language: ruby

cache: docker

services:
  - docker

install: true

# before_script:
#   -docker-compose up -d

script:
  - docker-compose -f docker-compose.test.yml run sut

after_script:
  - docker-compose down
