sudo: required
language: python
python:
- '2.7'
services:
- docker
env:
  matrix:
  - global:
    - DOCKER_COMPOSE_VERSION: 2
    - REPO=prontotools/pronto-woo-notifier
    - COMMIT=${TRAVIS_COMMIT::8}
install: true
before_script:
- docker build -t $REPO:$COMMIT -f ./compose/rails/Dockerfile .
script:
- docker-compose -f docker-compose.test.yml run sut
after_success:
- bash deploy.sh
after_script:
- docker-compose down
